//  supportivesmm and airgrow ,tntsmm,sakbasmm
export default [
	{
		linkType: 'profile',
		serviceId: 511,
		quantity: 100,
		price: 15,
		api: 'supportivesmm',
	},
	{
		linkType: 'profile',
		serviceId: 511,
		quantity: 100,
		price: 13,
		api: 'supportivesmm',
	},
	{
		linkType: 'profile',
		serviceId: 13787,
		quantity: 50,
		price: 8,
		api: 'sakbasmm',
	},
	{
		linkType: 'reel',
		serviceId: 602,
		quantity: 5000,
		price: 7,
		api: 'supportivesmm',
	},
	{
		linkType: 'reel',
		serviceId: 602,
		quantity: 10000,
		price: 12,
		api: 'supportivesmm',
	},
	{
		linkType: 'reel',
		serviceId: 602,
		quantity: 25000,
		price: 25,
		api: 'supportivesmm',
	},
	{
		linkType: 'reel',
		serviceId: 602,
		quantity: 50000,
		price: 45,
		api: 'supportivesmm',
	},
	// SupportiveSMM Instagram likes (post + reel)
	{
		linkType: 'reel',
		serviceId: 588,
		quantity: 1000,
		price: 30,
		api: 'supportivesmm',
	},
	{
		linkType: 'post',
		serviceId: 588,
		quantity: 1000,
		price: 30,
		api: 'supportivesmm',
	},
	{
		linkType: 'reel',
		serviceId: 588,
		quantity: 1000,
		price: 35,
		api: 'supportivesmm',
	},
	{
		linkType: 'post',
		serviceId: 588,
		quantity: 1000,
		price: 35,
		api: 'supportivesmm',
	},
];
